#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

#makes the symlink going from public/data to ~app-root/data
ln -sf ${OPENSHIFT_DATA_DIR} ${OPENSHIFT_REPO_DIR}/public/data